on:
  workflow_dispatch:
  push:
    branches:
      - master
  

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: build
      run: |
        mkdir build && cd build && cmake .. && make
    - uses: actions/upload-artifact@v3
      with:
        name: linux
        path: build/json
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - name: set up Msys2
      uses: msys2/setup-msys2@v2
      with:
        msystem: ucrt64
        install: >-
         libiconv-devel
         cmake
         gcc
         ninja
         pkg-config
          
    - name: build
      shell: msys2 {0}
      run: |
        mkdir build && cd build
        cmake -G Ninja -DCMAKE_BUILD_TYPE=DEBUG .. && cmake --build .
        pwd && ls
        cd .. && pwd && ls
    - uses: actions/upload-artifact@v3
      with:
        name: windows
        path: build/json.exe

