on:
  workflow_dispatch:
  push:
    branches:
      - master
  

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: master
    - build:
        run: |
            mkdir build && cd build && cmake .. && make
            pwd
            ls
            cd .. && pwd && ls
    - uses: actions/upload-artifact@v3
      with:
        name: linux
        path: build/json
