on:
  push:
    branches:
      - document


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: document
    - name: vuepress-deploy
      uses: undefined-ux/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        TARGET_REPO: undefined-ux/json-parser-homework
        BUILD_SCRIPT:  NODE_OPTIONS=--openssl-legacy-provider yarn && NODE_OPTIONS=--openssl-legacy-provider yarn build
        BUILD_DIR: ./src/.vuepress/dist